:doctype: manpage
:revnumber:
:manmanual: Opscan Manual
:mansource:
:man-linkstyle: pass:[blue R < >]
:stylesheet: adoc-readthedocs.css

:includedir: ../../../target/generated-picocli-docs

include::{includedir}/opscan-scan-short-put.adoc[tag=picocli-generated-man-section-header]

include::{includedir}/opscan-scan-short-put.adoc[tag=picocli-generated-man-section-name]

include::{includedir}/opscan-scan-short-put.adoc[tag=picocli-generated-man-section-synopsis]

include::{includedir}/opscan-scan-short-put.adoc[tag=picocli-generated-man-section-arguments]

include::{includedir}/opscan-scan-short-put.adoc[tag=picocli-generated-man-section-commands]

// tag::examples[]
== Examples

Search for naked or covered put opportunities in INTC between 30 and 60 days out (default).

----
opscan scan INTC short-put
----

=== Modifying days to expiry

To change your results to include different days to expiry (DTE), use `--min-dte`, `-m` and `--max-dte`, `-M` (Note - check if the underlying has an expiration in this time or you will get no results!)

----
opscan scan INTC short-put --min-dte=0 --max-dte=14
----
----
opscan scan INTC short-put -m 0 -M 14
----

=== Setting a minimum and maximum delta

To filter your results by the position's delta, use `--min-delta`, `-d` and `--max-delta`, `-D`.

Note that these values should always be positive, puts have negative delta but the tool will handle this. In this case, passing `0.2` will mean `-0.2` for puts.

----
opscan scan INTC short-put --min-delta=0.1 --max-delta=0.35
----

=== Setting a maximum strike

If you plan to only sell a put at or below a certain price, you can configure this with `--max-strike`, `-s`

----
opscan scan INTC short-put --max-strike=48
----

=== Setting a minimum ROI

==== Basic ROI

To filter your results by return on investment (`(premium / strike price) * 100`) use `--min-roi`, `-r`.

For example to require a minimum ROI of 2% use `2`.

----
opscan scan INTC short-put --min-roi=2
----

==== Annualized ROI

To filter your results by annualized ROI (`roi * (250 / daysToExpiry)`) use `--min-annualized-roi`, `-a`.

For example to require a minimum annualized ROI of 15% use `15`.

----
opscan scan INTC short-put --min-annualized-roi=15
----

=== Allowing "in the money"

By default only "out of the money" (i.e. strikes above the current stock price) will be returned. Set `--allow-in-the-money`, `-i` to change this.

----
opscan scan INTC short-put --allow-in-the-money
----

// end:examples[]

include::{includedir}/opscan-scan-short-put.adoc[tag=picocli-generated-man-section-options]

